// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQF5dpdeys6aMwTbO-nA8vIHXnkOu30g',
    appId: '1:463350930668:web:a9aece92cb6706083e59c9',
    messagingSenderId: '463350930668',
    projectId: 'neev-7b2f0',
    authDomain: 'neev-7b2f0.firebaseapp.com',
    storageBucket: 'neev-7b2f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALBZne3ZLPB9zzqHrPKi6Us40NApDPP-s',
    appId: '1:463350930668:android:8e19d64288dd59fd3e59c9',
    messagingSenderId: '463350930668',
    projectId: 'neev-7b2f0',
    storageBucket: 'neev-7b2f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ20umyFzvWIQHMQcRUxKTCTkeX71Tlao',
    appId: '1:463350930668:ios:cd040f5f7d3beff43e59c9',
    messagingSenderId: '463350930668',
    projectId: 'neev-7b2f0',
    storageBucket: 'neev-7b2f0.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ20umyFzvWIQHMQcRUxKTCTkeX71Tlao',
    appId: '1:463350930668:ios:cd040f5f7d3beff43e59c9',
    messagingSenderId: '463350930668',
    projectId: 'neev-7b2f0',
    storageBucket: 'neev-7b2f0.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaQF5dpdeys6aMwTbO-nA8vIHXnkOu30g',
    appId: '1:463350930668:web:5e8e8bb26148b4d53e59c9',
    messagingSenderId: '463350930668',
    projectId: 'neev-7b2f0',
    authDomain: 'neev-7b2f0.firebaseapp.com',
    storageBucket: 'neev-7b2f0.firebasestorage.app',
  );
}
